---
- hosts: localhost
  become: true
  pre_tasks:
  - name: update repositories
    ansible.builtin.package:
      update_cache: yes
    changed_when: False

  tasks:
    - name: say hello
      ansible.builtin.command: "echo 'hello'"

- tags:
  - test 

