
python
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      ansible.builtin.package:
        update_cache: yes
      changed_when: False

  tags:
    - test 

