- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: velociraptor
    minute: "*/10"
    job: ansible-pull -o -U https://github.com/jlacroix82/ansible_pull_tutorial.git > /dev/null
